Lesson 10: modal added
oleksay2006/onix-test-site pull request #4
Opened 2021-12-19 19:47 UTC by oleksay2006

2021-12-21 14:47 UTC, maryiv requested changes
После внесения правок, просьба повторно пингануть в слаке

2021-12-21 14:47 UTC, maryiv commented on src/components/AddTaskModal.vue
> +          input.new-input.new-description(
https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/date

2021-12-21 14:47 UTC, maryiv commented on src/components/AddTaskModal.vue
> +  components: {},
Пустые блоки нам ни к чему

2021-12-21 14:47 UTC, maryiv commented on src/components/AddTaskModal.vue
> +    ...mapState([]),
И тут

2021-12-21 14:47 UTC, maryiv commented on src/components/AddTaskModal.vue
> +    ...mapState([]),
Пока просто для информации, обратить внимание
https://next.vuex.vuejs.org/guide/composition-api.html

2021-12-21 14:47 UTC, maryiv commented on src/components/AddTaskModal.vue
> +    ...mapActions(["CREATE_NEW_TASK"]),
Можно без капса

2021-12-21 14:47 UTC, maryiv commented on src/components/TaskDetailsModal.vue
> +          a.save.Button(
https://v3.vuejs.org/guide/events.html#multiple-event-handlers
Обратить внимание на `prevent`

2021-12-21 14:47 UTC, maryiv commented on src/components/TaskDetailsModal.vue
> +          a.cancel.Button(href="#", v-on:click="removeEditTask()") Cancel
Кнопка отмены тоже должна появляться, когда у нас модалка в режиме редактирования
И позволяет отменить редактирование (вернуться в режим просмотра без сохранения изменений)

2021-12-21 14:47 UTC, maryiv commented on src/components/TaskDetailsModal.vue
> +        .message.task(v-show="NotEdit")
В нашем кейсе мы можем использовать условный оператор `v-if / v-else`

2021-12-21 14:47 UTC, maryiv commented on src/store/index.ts
> +      task.title = changedTask.title;
Изменение полей лучше сделать 1й операцией

2021-12-21 14:47 UTC, maryiv commented on src/views/Kanban.vue
> +      currentTask: {},
Желательно указать интерфейс

2021-12-21 14:47 UTC, maryiv commented on src/views/Kanban.vue
> +      return this.tasks.filter((t) => t.status == "to-do");
Почему не используем enum?

2021-12-21 15:24 UTC, oleksay2006 commented on src/components/AddTaskModal.vue
> +    ...mapActions(["CREATE_NEW_TASK"]),
Делаю так, потому что вы сказали весь код vuex сделать одним регистром

2022-01-10 15:58 UTC, maryiv approved these changes

2022-01-10 15:58 UTC, merged