Lesson 11
oleksay2006/onix-test-site pull request #5
Opened 2021-12-29 21:05 UTC by oleksay2006

2022-01-04 10:44 UTC, kovalenk requested changes
`На вкладке Kanban реализовать функционал изменения стиля карточки в зависимости от статуса с помощью getter функции. `
Забыл добавить.

2022-01-04 12:45 UTC, kovalenk commented on src/components/AddTaskModal.vue
> +          //- input.new-input.new-description(
Если данный код не будет использоваться то его желательно убирать

2022-01-04 12:47 UTC, kovalenk commented on src/components/AddTaskModal.vue
> +    console.log("AddTaskModal: ", this.isShow);
Тестовые логи тоже желательно чистить

2022-01-04 12:52 UTC, kovalenk commented on src/components/SearchTask.vue
> +      let obj = {
Не забываем добавлять типизацию

2022-01-04 12:52 UTC, kovalenk commented on src/components/SearchTask.vue
> +    sortProductsBySearchValue(value) {
Типизация

2022-01-04 12:58 UTC, kovalenk commented on src/components/TaskDetailsModal.vue
> +    Edit() {
Желательно придерживаться общему правилу прописи названий методов (camelCase) Поправить по всему проекту

2022-01-04 12:58 UTC, kovalenk commented on src/components/TaskDetailsModal.vue
> +        const changedTask = {
интерфейс

2022-01-04 13:04 UTC, kovalenk requested changes
`На вкладке Kanban реализовать функционал изменения стиля карточки в зависимости от статуса с помощью getter функции. `
Забыл добавить. 

Что можно улучшить: 
- добавь в  gitignore папку dist
- что-то не та с структурой (видимо раньше это было таблицей, но позже переделалось под обычные блоки) убери остатки тегов таблицы ( td.taskCard )
![image](https://user-images.githubusercontent.com/25953935/148057474-6e48b3ed-78ac-4964-b6d7-9d8d444a80a2.png)
- по стилям желательно использовать препроцессоры и использовать их возможности. 
- убрать ненужные коменты и логи

2022-01-06 07:45 UTC, kovalenk commented on src/components/TaskCard.vue
> +      return this.task.status == "to-do" ? true : false;
Здесь проверку можно упростить,  this.task.status == "to-do" вернёт тоже самое, ниже такие же случаи так что можешь их тоже поправить

2022-01-06 07:46 UTC, kovalenk commented on src/components/TaskCard.vue
> +      return this.task.status == "in-progress" ? true : false;
to-do, in-progress, done желательно кинуть в enums

2022-01-06 07:47 UTC, kovalenk commented on src/components/TaskCard.vue
>    p.time {{ this.task.time }}
в темплейтах this не обязательно писать

2022-01-06 07:48 UTC, kovalenk commented on src/components/TaskDetailsModal.vue
> +              :class="{ isDone: this.currentTask.status == 'done' }"
done в enum, this убрать

2022-01-06 07:51 UTC, kovalenk requested changes
11 lesson принимаю, поправь моменты которые описал выше

2022-01-06 09:50 UTC, kovalenk approved these changes

2022-01-10 16:00 UTC, maryiv commented on src/components/TaskCard.vue
> +      return this.task.status == "to-do" ? true : false;
this.task.status должен сравниваться не со строкой, а с созданным для статусов enum

2022-01-18 10:31 UTC, merged